// <auto-generated />
using System;
using DoorDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoorWebDB.Migrations
{
    [DbContext(typeof(DoorDbContext))]
    [Migration("20251223071242_AddRemarkToCourseFee")]
    partial class AddRemarkToCourseFee
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DoorDB.AccessEventLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("CardId1")
                        .HasColumnType("int");

                    b.Property<int>("CardId2")
                        .HasColumnType("int");

                    b.Property<int>("DoorNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FunctionCode")
                        .HasColumnType("int");

                    b.Property<int>("NodeId")
                        .HasColumnType("int");

                    b.Property<int>("PortNumber")
                        .HasColumnType("int");

                    b.Property<int>("UserAddress")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblAccessEventLog");
                });

            modelBuilder.Entity("DoorDB.TblAttendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AttendanceDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("AttendanceType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsTrigger")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("StudentPermissionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedUserId");

                    b.HasIndex("StudentPermissionId");

                    b.ToTable("tblAttendance");
                });

            modelBuilder.Entity("DoorDB.TblAttendanceFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id");

                    b.Property<decimal>("AdjustmentAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("單堂增減金額");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("單堂學費");

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int")
                        .HasComment("簽到記錄Id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("建立時間");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("扣課時數");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("修改時間");

                    b.Property<decimal>("SourceHoursTotalAmount")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("原始時數總金額");

                    b.Property<decimal>("UseSplitRatio")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("使用的拆帳比");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceId")
                        .IsUnique();

                    b.ToTable("tblAttendanceFee");
                });

            modelBuilder.Entity("DoorDB.TblAuditLog", b =>
                {
                    b.Property<int>("Serial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ActType")
                        .HasColumnType("int");

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Serial");

                    b.ToTable("tblAuditLog");
                });

            modelBuilder.Entity("DoorDB.TblClassroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tblClassroom");
                });

            modelBuilder.Entity("DoorDB.TblCloseAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BusinessIncome")
                        .HasColumnType("int")
                        .HasComment("營業收入 (學生學費)");

                    b.Property<int>("CloseAccountAmount")
                        .HasColumnType("int")
                        .HasComment("關帳結算金額 (昨日零用金收支 + 營業收入)");

                    b.Property<DateTime>("CloseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DepositAmount")
                        .HasColumnType("int")
                        .HasComment("提存金額");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("PettyIncome")
                        .HasColumnType("int")
                        .HasComment("零用金結餘");

                    b.Property<int>("YesterdayPettyIncome")
                        .HasColumnType("int")
                        .HasComment("昨日零用金結餘");

                    b.HasKey("Id");

                    b.ToTable("tblCloseAccount");
                });

            modelBuilder.Entity("DoorDB.TblCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CourseTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CourseTypeId");

                    b.ToTable("tblCourse");
                });

            modelBuilder.Entity("DoorDB.TblCourseFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("課程費用Id");

                    b.Property<int>("Amount")
                        .HasColumnType("int")
                        .HasComment("課程費用");

                    b.Property<string>("Category")
                        .HasColumnType("longtext")
                        .HasComment("類別 (個別班、團體班、不限)");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasComment("課程Id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("建立時間");

                    b.Property<string>("FeeCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("課程費用編號");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("繳費時數");

                    b.Property<int>("MaterialFee")
                        .HasColumnType("int")
                        .HasComment("預設教材費");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("修改時間");

                    b.Property<int>("OpenCourseAmount")
                        .HasColumnType("int")
                        .HasComment("開放課程費用");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasComment("課程說明");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasComment("排序");

                    b.Property<decimal>("SplitRatio")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("預設拆帳比例");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("tblCourseFee");
                });

            modelBuilder.Entity("DoorDB.TblCourseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tblCourseType");
                });

            modelBuilder.Entity("DoorDB.TblPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DiscountAmount")
                        .HasColumnType("int")
                        .HasComment("總額折扣");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ModifiedUserId")
                        .HasColumnType("int");

                    b.Property<int>("Pay")
                        .HasColumnType("int");

                    b.Property<string>("PayDate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("longtext")
                        .HasComment("結帳單號");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasComment("備註");

                    b.Property<int>("StudentPermissionFeeId")
                        .HasColumnType("int")
                        .HasComment("學生權限費用Id ([tblStudentPermissionFee].[Id])");

                    b.HasKey("Id");

                    b.HasIndex("ModifiedUserId");

                    b.HasIndex("StudentPermissionFeeId")
                        .IsUnique();

                    b.ToTable("tblPayment");
                });

            modelBuilder.Entity("DoorDB.TblPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("權限項目Id");

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasComment("權限日期起");

                    b.Property<string>("DateTo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.Property<string>("TimeFrom")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasComment("權限時間起");

                    b.Property<string>("TimeTo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("權限項目所屬使用者([tblUser].[Id])");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("tblPermission");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateFrom = "2024/07/21",
                            DateTo = "2124/07/21",
                            Days = "1,2,3,4,5,6,7",
                            IsDelete = false,
                            IsEnable = true,
                            PermissionLevel = 1,
                            TimeFrom = "00:00",
                            TimeTo = "24:00",
                            UserId = 51
                        },
                        new
                        {
                            Id = 2,
                            DateFrom = "2024/07/21",
                            DateTo = "2124/07/21",
                            Days = "",
                            IsDelete = false,
                            IsEnable = true,
                            PermissionLevel = 1,
                            TimeFrom = "00:00",
                            TimeTo = "24:00",
                            UserId = 52
                        });
                });

            modelBuilder.Entity("DoorDB.TblPermissionGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tblPermissionGroup");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "大門"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Car教室"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sunny教室"
                        },
                        new
                        {
                            Id = 4,
                            Name = "儲藏室"
                        });
                });

            modelBuilder.Entity("DoorDB.TblQRCodeStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QRCodeData")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("qrcodeTxt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("userTag")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tblQRCodeStorage");
                });

            modelBuilder.Entity("DoorDB.TblRefund", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("流水號");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("建立時間");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否刪除");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("修改時間");

                    b.Property<string>("ReceiptNumber")
                        .HasColumnType("longtext")
                        .HasComment("結帳單號");

                    b.Property<int>("RefundAmount")
                        .HasColumnType("int")
                        .HasComment("退款金額");

                    b.Property<string>("RefundDate")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasComment("退款日期");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasComment("備註");

                    b.Property<int>("StudentPermissionFeeId")
                        .HasColumnType("int")
                        .HasComment("學生權限費用Id");

                    b.HasKey("Id");

                    b.HasIndex("StudentPermissionFeeId");

                    b.ToTable("tblRefund");
                });

            modelBuilder.Entity("DoorDB.TblRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("tblRole");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CanDelete = false,
                            CreatedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4584),
                            CreatorUserId = 1,
                            Description = "管理者",
                            IsDelete = false,
                            IsEnable = true,
                            ModifiedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4585),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CanDelete = false,
                            CreatedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4587),
                            CreatorUserId = 1,
                            Description = "老師",
                            IsDelete = false,
                            IsEnable = true,
                            ModifiedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4587),
                            Name = "User"
                        },
                        new
                        {
                            Id = 3,
                            CanDelete = false,
                            CreatedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4588),
                            CreatorUserId = 1,
                            Description = "學生",
                            IsDelete = false,
                            IsEnable = true,
                            ModifiedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4589),
                            Name = "User"
                        },
                        new
                        {
                            Id = 4,
                            CanDelete = false,
                            CreatedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4590),
                            CreatorUserId = 1,
                            Description = "值班人員",
                            IsDelete = false,
                            IsEnable = true,
                            ModifiedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4590),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("DoorDB.TblSchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ClassroomId")
                        .HasColumnType("int")
                        .HasComment("教室Id ([tblClassroom].[Id])");

                    b.Property<int>("CourseMode")
                        .HasColumnType("int")
                        .HasComment("課程模式 1=現場 2=視訊");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasComment("課程結束時間");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("QRCodeContent")
                        .HasColumnType("longtext")
                        .HasComment("QR Code 內容");

                    b.Property<string>("Remark")
                        .HasColumnType("longtext")
                        .HasComment("備註");

                    b.Property<string>("ScheduleDate")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasComment("課程日期");

                    b.Property<int>("ScheduleMode")
                        .HasColumnType("int")
                        .HasComment("排課模式 1=每週固定 2=每兩週固定 3=單次課程");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasComment("課程開始時間");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasComment("課程狀態 1=正常 2=取消 3=延期");

                    b.Property<int>("StudentPermissionId")
                        .HasColumnType("int")
                        .HasComment("學生權限Id ([tblStudentPermission].[Id])");

                    b.HasKey("Id");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("StudentPermissionId");

                    b.ToTable("tblSchedule");
                });

            modelBuilder.Entity("DoorDB.TblStudentPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("權限項目Id");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasComment("權限項目所屬使用者([tblCourse].[Id])");

                    b.Property<string>("DateFrom")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasComment("權限日期起");

                    b.Property<string>("DateTo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Days")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasComment("紀錄Id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasComment("權限項目所屬老師([tblUser].[Id])");

                    b.Property<string>("TimeFrom")
                        .IsRequired()
                        .HasColumnType("varchar(5)")
                        .HasComment("權限時間起");

                    b.Property<string>("TimeTo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("用途類型 1=上課 2=租借教室");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasComment("權限項目所屬使用者([tblUser].[Id])");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("UserId");

                    b.ToTable("tblStudentPermission");
                });

            modelBuilder.Entity("DoorDB.TblStudentPermissionFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id");

                    b.Property<decimal?>("CourseSplitRatio")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("課程拆帳比");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("建立時間");

                    b.Property<decimal>("Hours")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("課程時數");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)")
                        .HasComment("是否刪除");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("修改時間");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime(6)")
                        .HasComment("繳款日期");

                    b.Property<int>("StudentPermissionId")
                        .HasColumnType("int")
                        .HasComment("學生權限Id");

                    b.Property<decimal?>("TeacherSplitRatio")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("老師拆帳比");

                    b.Property<int>("TotalAmount")
                        .HasColumnType("int")
                        .HasComment("總金額");

                    b.HasKey("Id");

                    b.HasIndex("StudentPermissionId");

                    b.ToTable("tblStudentPermissionFee");
                });

            modelBuilder.Entity("DoorDB.TblTeacherSettlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("Id");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("建立時間");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)")
                        .HasComment("修改時間");

                    b.Property<decimal>("SplitRatio")
                        .HasColumnType("decimal(65,30)")
                        .HasComment("老師拆帳比例");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int")
                        .HasComment("老師Id");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.ToTable("tblTeacherSettlement");
                });

            modelBuilder.Entity("DoorDB.TblUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("IDcard")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDelete")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsEnable")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastLoginIP")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastLoginTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ModifiedTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RelationshipTitle")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("選課狀態 預設0,1在學,2停課,3約課");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("locale")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("tblUser");

                    b.HasData(
                        new
                        {
                            Id = 51,
                            AccountType = "LOCAL",
                            Address = "",
                            ContactPerson = "",
                            ContactPhone = "",
                            CreateTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4566),
                            DisplayName = "Administrator",
                            Email = "",
                            IDcard = "",
                            IsDelete = false,
                            IsEnable = true,
                            LastLoginIP = "",
                            ModifiedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4578),
                            Phone = "0",
                            RelationshipTitle = "",
                            Secret = "1qaz2wsx",
                            Type = 0,
                            Username = "admin",
                            locale = 1
                        },
                        new
                        {
                            Id = 52,
                            AccountType = "LOCAL",
                            Address = "",
                            ContactPerson = "",
                            ContactPhone = "",
                            CreateTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4580),
                            DisplayName = "臨時大門",
                            Email = "",
                            IDcard = "",
                            IsDelete = false,
                            IsEnable = true,
                            LastLoginIP = "",
                            ModifiedTime = new DateTime(2025, 12, 23, 15, 12, 42, 346, DateTimeKind.Local).AddTicks(4580),
                            Phone = "0",
                            RelationshipTitle = "",
                            Secret = "1qaz2wsx",
                            Type = 0,
                            Username = "TemDoor",
                            locale = 1
                        });
                });

            modelBuilder.Entity("TblPermissionGroupTblStudentPermission", b =>
                {
                    b.Property<int>("PermissionGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("StudentPermissionsId")
                        .HasColumnType("int");

                    b.HasKey("PermissionGroupsId", "StudentPermissionsId");

                    b.HasIndex("StudentPermissionsId");

                    b.ToTable("TblPermissionGroupTblStudentPermission");
                });

            modelBuilder.Entity("TblPermissionTblPermissionGroup", b =>
                {
                    b.Property<int>("PermissionGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.HasKey("PermissionGroupsId", "PermissionsId");

                    b.HasIndex("PermissionsId");

                    b.ToTable("TblPermissionTblPermissionGroup");

                    b.HasData(
                        new
                        {
                            PermissionGroupsId = 1,
                            PermissionsId = 1
                        },
                        new
                        {
                            PermissionGroupsId = 2,
                            PermissionsId = 1
                        },
                        new
                        {
                            PermissionGroupsId = 3,
                            PermissionsId = 1
                        },
                        new
                        {
                            PermissionGroupsId = 4,
                            PermissionsId = 1
                        },
                        new
                        {
                            PermissionGroupsId = 1,
                            PermissionsId = 2
                        });
                });

            modelBuilder.Entity("TblQRCodeStorageTblUser", b =>
                {
                    b.Property<int>("QRCodesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("QRCodesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TblQRCodeStorageTblUser");
                });

            modelBuilder.Entity("TblRoleTblUser", b =>
                {
                    b.Property<int>("RolesId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("RolesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("TblRoleTblUser");

                    b.HasData(
                        new
                        {
                            RolesId = 1,
                            UsersId = 51
                        },
                        new
                        {
                            RolesId = 4,
                            UsersId = 52
                        });
                });

            modelBuilder.Entity("DoorDB.TblAttendance", b =>
                {
                    b.HasOne("DoorDB.TblUser", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorDB.TblStudentPermission", "StudentPermission")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifiedUser");

                    b.Navigation("StudentPermission");
                });

            modelBuilder.Entity("DoorDB.TblAttendanceFee", b =>
                {
                    b.HasOne("DoorDB.TblAttendance", "Attendance")
                        .WithOne("AttendanceFee")
                        .HasForeignKey("DoorDB.TblAttendanceFee", "AttendanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attendance");
                });

            modelBuilder.Entity("DoorDB.TblCourse", b =>
                {
                    b.HasOne("DoorDB.TblCourseType", "CourseType")
                        .WithMany("Courses")
                        .HasForeignKey("CourseTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CourseType");
                });

            modelBuilder.Entity("DoorDB.TblCourseFee", b =>
                {
                    b.HasOne("DoorDB.TblCourse", "Course")
                        .WithOne("CourseFee")
                        .HasForeignKey("DoorDB.TblCourseFee", "CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("DoorDB.TblPayment", b =>
                {
                    b.HasOne("DoorDB.TblUser", "ModifiedUser")
                        .WithMany()
                        .HasForeignKey("ModifiedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorDB.TblStudentPermissionFee", "StudentPermissionFee")
                        .WithOne("Payment")
                        .HasForeignKey("DoorDB.TblPayment", "StudentPermissionFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ModifiedUser");

                    b.Navigation("StudentPermissionFee");
                });

            modelBuilder.Entity("DoorDB.TblPermission", b =>
                {
                    b.HasOne("DoorDB.TblUser", "User")
                        .WithOne("Permission")
                        .HasForeignKey("DoorDB.TblPermission", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoorDB.TblRefund", b =>
                {
                    b.HasOne("DoorDB.TblStudentPermissionFee", "StudentPermissionFee")
                        .WithMany()
                        .HasForeignKey("StudentPermissionFeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentPermissionFee");
                });

            modelBuilder.Entity("DoorDB.TblSchedule", b =>
                {
                    b.HasOne("DoorDB.TblClassroom", "Classroom")
                        .WithMany("Schedules")
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorDB.TblStudentPermission", "StudentPermission")
                        .WithMany("Schedules")
                        .HasForeignKey("StudentPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Classroom");

                    b.Navigation("StudentPermission");
                });

            modelBuilder.Entity("DoorDB.TblStudentPermission", b =>
                {
                    b.HasOne("DoorDB.TblCourse", "Course")
                        .WithMany("CourseStudentPermissions")
                        .HasForeignKey("CourseId");

                    b.HasOne("DoorDB.TblUser", "Teacher")
                        .WithMany("TeacherStudentPermissions")
                        .HasForeignKey("TeacherId");

                    b.HasOne("DoorDB.TblUser", "User")
                        .WithMany("StudentPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Teacher");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DoorDB.TblStudentPermissionFee", b =>
                {
                    b.HasOne("DoorDB.TblStudentPermission", "StudentPermission")
                        .WithMany("StudentPermissionFees")
                        .HasForeignKey("StudentPermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StudentPermission");
                });

            modelBuilder.Entity("DoorDB.TblTeacherSettlement", b =>
                {
                    b.HasOne("DoorDB.TblUser", "Teacher")
                        .WithOne("TeacherSettlement")
                        .HasForeignKey("DoorDB.TblTeacherSettlement", "TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("DoorDB.TblUser", b =>
                {
                    b.HasOne("DoorDB.TblUser", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TblPermissionGroupTblStudentPermission", b =>
                {
                    b.HasOne("DoorDB.TblPermissionGroup", null)
                        .WithMany()
                        .HasForeignKey("PermissionGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorDB.TblStudentPermission", null)
                        .WithMany()
                        .HasForeignKey("StudentPermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblPermissionTblPermissionGroup", b =>
                {
                    b.HasOne("DoorDB.TblPermissionGroup", null)
                        .WithMany()
                        .HasForeignKey("PermissionGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorDB.TblPermission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblQRCodeStorageTblUser", b =>
                {
                    b.HasOne("DoorDB.TblQRCodeStorage", null)
                        .WithMany()
                        .HasForeignKey("QRCodesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorDB.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TblRoleTblUser", b =>
                {
                    b.HasOne("DoorDB.TblRole", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DoorDB.TblUser", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DoorDB.TblAttendance", b =>
                {
                    b.Navigation("AttendanceFee");
                });

            modelBuilder.Entity("DoorDB.TblClassroom", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DoorDB.TblCourse", b =>
                {
                    b.Navigation("CourseFee");

                    b.Navigation("CourseStudentPermissions");
                });

            modelBuilder.Entity("DoorDB.TblCourseType", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("DoorDB.TblStudentPermission", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Schedules");

                    b.Navigation("StudentPermissionFees");
                });

            modelBuilder.Entity("DoorDB.TblStudentPermissionFee", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("DoorDB.TblUser", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Permission")
                        .IsRequired();

                    b.Navigation("StudentPermissions");

                    b.Navigation("TeacherSettlement");

                    b.Navigation("TeacherStudentPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
