// <auto-generated />
using System;
using DoorDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DoorWebDB.Migrations
{
    [DbContext(typeof(DoorDbContext))]
    [Migration("20251024141812_AddRecordIdToTblStudentPermission")]
    partial class AddRecordIdToTblStudentPermission
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);
            modelBuilder.Entity("DoorDB.TblStudentPermission", b =>
                {
                    b.Property<int>("RecordId")
                        .HasColumnType("int")
                        .HasComment("紀錄Id");
                });
#pragma warning restore 612, 618
        }
    }
}
